import json

NOTAS = {
    "ASD-100":   {"topo": ["Pimenta Preta", "Lavanda", "Noz-Moscada"], "coracao": ["Cedro", "Rosa", "Gerânio"], "base": ["Âmbar", "Oud", "Almíscar", "Sândalo"]},
    "ASDB-100":  {"topo": ["Ameixa Mirabelle", "Pimenta Rosa", "Lavanda"], "coracao": ["Cacau", "Noz-Moscada", "Davana"], "base": ["Baunilha Bourbon", "Âmbar", "Vetiver"]},
    "ASDE-100":  {"topo": ["Toranja", "Pimenta Rosa", "Açafrão"], "coracao": ["Tabaco", "Cedro", "Baunilha"], "base": ["Patchouli", "Olíbano", "Cashmeran", "Âmbar Seco"]},
    "ASDZ-100":  {"topo": ["Lavanda", "Pimenta Preta"], "coracao": ["Água de Coco", "Íris", "Sal"], "base": ["Baunilha", "Incenso"]},
    "FKG-100":   {"topo": ["Tuberosa", "Sal"], "coracao": ["Âmbar", "Tonka", "Cashmeran"], "base": ["Cedro", "Vetiver", "Labdanum"]},
    "FKB-100":   {"topo": ["Maçã", "Bergamota", "Gengibre"], "coracao": ["Lavanda", "Sálvia", "Bagas de Zimbro", "Gerânio"], "base": ["Tonka", "Cedro", "Amberwood", "Vetiver"]},
    "FKP-100":   {"topo": ["Bergamota", "Pimenta Rosa", "Cardamomo"], "coracao": ["Goiaba", "Lavanda", "Gengibre"], "base": ["Incenso", "Palo Santo", "Sândalo"]},
    "FKR-100":   {"topo": ["Frutas", "Lírio", "Romã", "Aldeídos"], "coracao": ["Tuberosa", "Jasmim", "Gardênia", "Ylang-Ylang", "Rosa", "Peônia"], "base": ["Baunilha", "Almíscar Branco", "Sândalo", "Ambroxan"]},
    "YARA-100":  {"topo": ["Mandarina", "Heliotropo", "Orquídea"], "coracao": ["Frutas Tropicais", "Notas Gourmand"], "base": ["Baunilha", "Sândalo", "Almíscar"]},
    "YRC-100":   {"topo": ["Tangerina Verde", "Groselha Preta"], "coracao": ["Gardênia", "Bala de Morango"], "base": ["Sândalo", "Xarope de Baunilha", "Almíscar", "Âmbar"]},
    "YRE-100":   {"topo": ["S'mores de Morango", "Groselha Preta"], "coracao": ["Jasmim", "Flor de Laranjeira"], "base": ["Baunilha", "Caramelo", "Âmbar", "Almíscar"]},
    "YRT-100":   {"topo": ["Manga", "Coco", "Maracujá"], "coracao": ["Jasmim", "Flor de Laranjeira", "Heliotropo"], "base": ["Baunilha", "Almíscar", "Cashmeran"]},
    "YRM-100":   {"topo": ["Pêra", "Pimenta Rosa", "Groselha Preta"], "coracao": ["Tuberosa", "Jasmim", "Amêndoa"], "base": ["Baunilha", "Cashmeran", "Patchouli"]},
    "KMR-100":   {"topo": ["Canela", "Noz-Moscada", "Bergamota"], "coracao": ["Tâmaras", "Pralinê", "Tuberosa"], "base": ["Baunilha", "Tonka", "Amberwood", "Mirra", "Benjoim"]},
    "KMQ-100":   {"topo": ["Canela", "Cardamomo", "Gengibre"], "coracao": ["Pralinê", "Frutas Cristalizadas", "Flores Brancas"], "base": ["Café", "Baunilha", "Tonka", "Benjoim", "Almíscar"]},
    "KMD-100":   {"topo": ["Especiarias", "Pimenta", "Mandarina"], "coracao": ["Incenso", "Labdanum", "Flor de Laranjeira", "Patchouli"], "base": ["Tabaco", "Pralinê", "Âmbar", "Tonka", "Benjoim"]},
    "WZR-100":   {"topo": ["Bergamota", "Pimenta Rosa"], "coracao": ["Sândalo", "Almíscar", "Notas Florais"], "base": ["Âmbar", "Madeiras Orientais"]},
    "SFR-100":   {"topo": ["Bergamota", "Limão"], "coracao": ["Notas Florais", "Especiarias"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "AMR-100":   {"topo": ["Bergamota", "Cardamomo"], "coracao": ["Rosa", "Notas Orientais"], "base": ["Oud", "Âmbar", "Almíscar"]},
    "MMI-100":   {"topo": ["Bergamota", "Pimenta Rosa", "Toranja"], "coracao": ["Sândalo", "Notas Amadeiradas"], "base": ["Âmbar", "Almíscar", "Baunilha", "Tonka"]},
    "BFH-100":   {"topo": ["Bergamota", "Especiarias"], "coracao": ["Oud", "Rosa", "Notas Florais"], "base": ["Âmbar", "Sândalo", "Almíscar"]},
    "BNB-100":   {"topo": ["Frutas", "Bergamota"], "coracao": ["Rosa", "Peônia", "Notas Florais"], "base": ["Almíscar", "Baunilha", "Sândalo"]},
    "BS-100":    {"topo": ["Frutas Tropicais", "Bergamota"], "coracao": ["Notas Florais", "Coco"], "base": ["Baunilha", "Almíscar", "Sândalo"]},
    "BAT-100":   {"topo": ["Bergamota", "Frutas"], "coracao": ["Oud", "Flores Brancas"], "base": ["Âmbar", "Almíscar", "Sândalo"]},
    "BG-100":    {"topo": ["Bergamota", "Especiarias"], "coracao": ["Oud", "Rosa"], "base": ["Âmbar", "Sândalo", "Almíscar"]},
    "THG-100":   {"topo": ["Bergamota", "Açafrão"], "coracao": ["Rosa", "Notas Florais Douradas"], "base": ["Oud", "Âmbar", "Almíscar"]},
    "THS-100":   {"topo": ["Bergamota", "Notas Frescas"], "coracao": ["Notas Florais", "Madeiras"], "base": ["Almíscar", "Cedro", "Âmbar"]},
    "RYE-100":   {"topo": ["Bergamota", "Pimenta Rosa"], "coracao": ["Notas Florais", "Especiarias"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "EME-100":   {"topo": ["Bergamota", "Cardamomo"], "coracao": ["Rosa", "Oud", "Notas Orientais"], "base": ["Âmbar", "Almíscar", "Sândalo"]},
    "AFF-100":   {"topo": ["Bergamota", "Especiarias"], "coracao": ["Rosa", "Oud", "Notas Florais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "LATANG-100":{"topo": ["Bergamota", "Frutas"], "coracao": ["Notas Florais Orientais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "LATATH-100":{"topo": ["Bergamota", "Especiarias Raras"], "coracao": ["Oud", "Rosa", "Notas Orientais Profundas"], "base": ["Âmbar", "Almíscar", "Sândalo"]},
    "LATDAL-100":{"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais", "Notas Gourmand"], "base": ["Baunilha", "Âmbar", "Almíscar"]},
    "LATECL-100":{"topo": ["Bergamota", "Frutas Cítricas"], "coracao": ["Notas Gourmand", "Caramelo"], "base": ["Baunilha", "Âmbar", "Tonka"]},
    "LATECLB-100":{"topo": ["Banana", "Frutas"], "coracao": ["Caramelo", "Notas Gourmand"], "base": ["Baunilha", "Tonka", "Âmbar"]},
    "LATECLP-100":{"topo": ["Pistache", "Frutas"], "coracao": ["Notas Gourmand", "Caramelo"], "base": ["Baunilha", "Tonka", "Âmbar"]},
    "LATHER-100":{"topo": ["Frutas", "Pêra"], "coracao": ["Notas Florais", "Notas Gourmand"], "base": ["Baunilha", "Almíscar", "Âmbar"]},
    "LATJAS-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Aromáticas", "Florais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "LATKOA-100":{"topo": ["Especiarias", "Bergamota"], "coracao": ["Rosa", "Oud", "Notas Orientais"], "base": ["Âmbar", "Sândalo", "Almíscar"]},
    "LATLAY-100":{"topo": ["Frutas", "Cítricas"], "coracao": ["Notas Florais Suaves"], "base": ["Almíscar", "Baunilha", "Madeiras"]},
    "LATMAB-100":{"topo": ["Bergamota", "Pimenta Preta"], "coracao": ["Sálvia", "Notas Aromáticas"], "base": ["Âmbar", "Almíscar", "Cedro"]},
    "LATMAG-100":{"topo": ["Bergamota", "Maçã", "Especiarias"], "coracao": ["Lavanda", "Notas Aromáticas"], "base": ["Âmbar", "Tonka", "Almíscar"]},
    "LATMAL-100":{"topo": ["Bergamota", "Maçã"], "coracao": ["Notas Aromáticas", "Florais"], "base": ["Âmbar", "Cedro", "Almíscar"]},
    "LATNEK-100":{"topo": ["Especiarias Raras", "Bergamota"], "coracao": ["Oud", "Rosa", "Notas Orientais"], "base": ["Âmbar", "Almíscar", "Sândalo"]},
    "LATPET-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Florais", "Madeiras"], "base": ["Âmbar", "Almíscar", "Cedro"]},
    "LATSMN-100":{"topo": ["Bergamota", "Frutas"], "coracao": ["Notas Florais", "Notas Amadeiradas"], "base": ["Âmbar", "Almíscar", "Madeiras Negras"]},
    "LATTKF-100":{"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais Femininas"], "base": ["Almíscar", "Baunilha", "Sândalo"]},
    "LATTKM-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Aromáticas", "Florais"], "base": ["Âmbar", "Almíscar", "Cedro"]},
    "LATVIC-100":{"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais", "Rosas"], "base": ["Almíscar", "Baunilha", "Âmbar"]},
    "sbh-100":   {"topo": ["Bergamota", "Frutas Cítricas"], "coracao": ["Notas Florais"], "base": ["Almíscar", "Âmbar", "Madeiras"]},
    "sbs-100":   {"topo": ["Frutas", "Açúcar"], "coracao": ["Notas Florais Adocicadas"], "base": ["Baunilha", "Almíscar", "Âmbar"]},
    "drt-100":   {"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais", "Rosa"], "base": ["Almíscar", "Âmbar", "Madeiras"]},
    "ALWEQA-100":{"topo": ["Especiarias", "Bergamota"], "coracao": ["Notas Amadeiradas", "Florais"], "base": ["Oud", "Âmbar", "Almíscar"]},
    "ALWSHA-100":{"topo": ["Rosa", "Frutas"], "coracao": ["Notas Florais", "Rosa"], "base": ["Almíscar", "Âmbar", "Madeiras"]},
    "RYA-100":   {"topo": ["Bergamota", "Especiarias"], "coracao": ["Rosa", "Notas Orientais"], "base": ["Âmbar", "Oud", "Almíscar"]},
    "AZF-100":   {"topo": ["Bergamota", "Notas Frescas"], "coracao": ["Notas Aquáticas", "Florais"], "base": ["Almíscar", "Madeiras", "Âmbar"]},
    "ABR-100":   {"topo": ["Especiarias", "Bergamota"], "coracao": ["Rosa", "Notas Orientais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "ORIANO-100":{"topo": ["Especiarias", "Frutas"], "coracao": ["Rosa", "Notas Orientais Escuras"], "base": ["Âmbar Negro", "Oud", "Almíscar"]},
    "ORIOSA-100":{"topo": ["Açafrão", "Especiarias"], "coracao": ["Oud", "Rosa"], "base": ["Âmbar", "Sândalo", "Almíscar"]},
    "ORIRBL-100":{"topo": ["Bergamota", "Notas Frescas"], "coracao": ["Notas Aromáticas", "Florais"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "ORIVGO-100":{"topo": ["Especiarias Douradas", "Bergamota"], "coracao": ["Rosa", "Notas Orientais"], "base": ["Âmbar Dourado", "Almíscar", "Sândalo"]},
    "CNI-100":   {"topo": ["Toranja", "Limão", "Hortelã", "Pimenta Rosa", "Coentro"], "coracao": ["Gengibre", "Melão", "Jasmim", "Noz-Moscada"], "base": ["Incenso", "Sândalo", "Âmbar", "Cedro", "Patchouli", "Labdanum"]},
    "CNE-100":   {"topo": ["Toranja", "Maçã", "Bergamota"], "coracao": ["Notas Florais", "Especiarias"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "CNW-100":   {"topo": ["Bergamota", "Notas Cítricas"], "coracao": ["Jasmim", "Flores Brancas"], "base": ["Baunilha", "Almíscar", "Sândalo"]},
    "CNU-100":   {"topo": ["Açafrão", "Jasmim"], "coracao": ["Amberwood", "Âmbar-Gris"], "base": ["Resina de Abeto", "Cedro"]},
    "CDN-100":   {"topo": ["Limão", "Abacaxi", "Bergamota", "Groselha Preta", "Maçã"], "coracao": ["Bergamota", "Notas Birch", "Jasmim"], "base": ["Patchouli", "Oud", "Almíscar", "Baunilha", "Âmbar"]},
    "CNM-100":   {"topo": ["Lichia", "Bergamota", "Pimenta Rosa"], "coracao": ["Íris"], "base": ["Pralinê", "Ambroxan", "Sândalo"]},
    "CNMT-100":  {"topo": ["Bergamota", "Frutas", "Notas Aquáticas"], "coracao": ["Violeta", "Almíscar Aquático"], "base": ["Ambroxan", "Vetiver", "Almíscar"]},
    "CNS-100":   {"topo": ["Bergamota", "Limão", "Lima", "Groselha Preta", "Gengibre"], "coracao": ["Rosa", "Íris", "Jasmim"], "base": ["Ambroxan", "Almíscar", "Sândalo", "Cedro"]},
    "ARMBLI-100":{"topo": ["Bergamota", "Frutas"], "coracao": ["Notas Florais", "Rosas"], "base": ["Almíscar", "Âmbar", "Madeiras"]},
    "ARMIMP-100":{"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais Orientais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "ARMLIO-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Aromáticas", "Florais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "ARMOAD-100":{"topo": ["Especiarias", "Bergamota"], "coracao": ["Oud", "Notas Orientais"], "base": ["Âmbar", "Almíscar", "Sândalo"]},
    "ARMOCA-100":{"topo": ["Frutas", "Doces"], "coracao": ["Notas Gourmand"], "base": ["Baunilha", "Âmbar", "Almíscar"]},
    "ARMOMH-100":{"topo": ["Bergamota", "Pimenta Preta"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Âmbar", "Almíscar"]},
    "ARMOLI-100":{"topo": ["Limão", "Notas Cítricas"], "coracao": ["Notas Florais Frescas"], "base": ["Almíscar", "Cedro", "Âmbar"]},
    "ARMOMA-100":{"topo": ["Mandarina", "Notas Cítricas"], "coracao": ["Notas Florais Frescas"], "base": ["Almíscar", "Madeiras", "Âmbar"]},
    "ARMOMS-100":{"topo": ["Marshmallow", "Frutas"], "coracao": ["Notas Gourmand", "Florais"], "base": ["Baunilha", "Almíscar", "Âmbar"]},
    "ARMOWI-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Âmbar", "Almíscar"]},
    "LQB-100":   {"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Amadeiradas"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "SCG-100":   {"topo": ["Bergamota", "Notas Frescas"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "VCF-100":   {"topo": ["Especiarias", "Notas Quentes"], "coracao": ["Madeiras", "Resinas"], "base": ["Âmbar", "Almíscar", "Baunilha"]},
    "VCB-100":   {"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "VNS-100":   {"topo": ["Frutas Vermelhas", "Especiarias"], "coracao": ["Rosa", "Notas Florais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "VNO-100":   {"topo": ["Especiarias", "Frutas"], "coracao": ["Notas Florais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "FRACHA-100":{"topo": ["Chocolate", "Frutas"], "coracao": ["Notas Gourmand"], "base": ["Baunilha", "Âmbar", "Almíscar"]},
    "FRACOC-100":{"topo": ["Cacau", "Frutas"], "coracao": ["Notas Gourmand"], "base": ["Baunilha", "Âmbar", "Almíscar"]},
    "FRADIA-100":{"topo": ["Açafrão", "Especiarias"], "coracao": ["Oud", "Rosa"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "FRALUS-100":{"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais"], "base": ["Baunilha", "Âmbar", "Almíscar"]},
    "FRASPM-100":{"topo": ["Especiarias", "Bergamota"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Âmbar", "Almíscar"]},
    "FRASPW-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "FRAVBI-100":{"topo": ["Flores Brancas", "Frutas"], "coracao": ["Notas Florais Brancas"], "base": ["Almíscar", "Baunilha", "Âmbar"]},
    "FRAVBF-100":{"topo": ["Especiarias", "Bergamota"], "coracao": ["Notas Amadeiradas"], "base": ["Âmbar Negro", "Almíscar", "Madeiras"]},
    "FRAVSA-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Amadeiradas"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "AFN9AM-100":{"topo": ["Bergamota", "Notas Aquáticas"], "coracao": ["Notas Marinhas", "Florais"], "base": ["Almíscar", "Âmbar", "Madeiras"]},
    "AFN9PMB-100":{"topo": ["Bergamota", "Pimenta Preta"], "coracao": ["Notas Aromáticas", "Especiadas"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "AFN9PMEL-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Orientais", "Especiadas"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "AFN9PMF-100":{"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais"], "base": ["Baunilha", "Almíscar", "Âmbar"]},
    "AFNKIA-100":{"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais Angélicas"], "base": ["Almíscar", "Baunilha", "Âmbar"]},
    "AFNTUR-100":{"topo": ["Bergamota", "Notas Frescas"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "ALHFRE-100":{"topo": ["Aldeídos", "Bergamota", "Pêssego"], "coracao": ["Flor de Laranjeira", "Lírio-do-Vale"], "base": ["Almíscar", "Baunilha", "Âmbar", "Oud Delicado"]},
    "ALHLEI-100":{"topo": ["Bergamota", "Notas Verdes"], "coracao": ["Notas Florais", "Aromáticas"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "ALHOLA-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Amadeiradas", "Aromáticas"], "base": ["Madeiras", "Âmbar", "Almíscar"]},
    "ALHCON-100":{"topo": ["Bergamota", "Frutas"], "coracao": ["Notas Florais Cremosas"], "base": ["Almíscar", "Baunilha", "Âmbar"]},
    "ALHHAR-100":{"topo": ["Bergamota", "Notas Frescas"], "coracao": ["Notas Florais Harmônicas"], "base": ["Almíscar", "Madeiras", "Âmbar"]},
    "ALHOUD-100":{"topo": ["Especiarias", "Bergamota"], "coracao": ["Oud", "Rosa"], "base": ["Âmbar", "Almíscar", "Sândalo"]},
    "ALHAOC-100":{"topo": ["Bergamota", "Notas Defumadas"], "coracao": ["Oud", "Notas de Carbono"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "ALHAOG-100":{"topo": ["Bergamota", "Notas Verdes", "Notas Frutadas"], "coracao": ["Melão", "Abacaxi", "Âmbar", "Notas Gourmand"], "base": ["Baunilha", "Almíscar", "Notas Amadeiradas"]},
    "ALHAOR-100":{"topo": ["Bergamota", "Frutas Vermelhas"], "coracao": ["Notas Florais", "Âmbar"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "ALHAOW-100":{"topo": ["Bergamota", "Notas Frescas"], "coracao": ["Notas Florais Brancas"], "base": ["Almíscar", "Baunilha", "Âmbar"]},
    "ALHLAC-100":{"topo": ["Bergamota", "Notas Cítricas"], "coracao": ["Notas Florais Celestiais"], "base": ["Almíscar", "Madeiras", "Âmbar"]},
    "ALHLAI-100":{"topo": ["Bergamota", "Notas Cítricas"], "coracao": ["Íris", "Notas Florais"], "base": ["Almíscar", "Madeiras", "Âmbar"]},
    "ALHMB-100": {"topo": ["Bergamota", "Notas Frescas"], "coracao": ["Notas Florais Brancas"], "base": ["Almíscar", "Baunilha", "Âmbar"]},
    "ALHMR-100": {"topo": ["Frutas Vermelhas", "Bergamota"], "coracao": ["Rosa", "Notas Florais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "ALHPAL-100":{"topo": ["Bergamota", "Notas Frutadas"], "coracao": ["Notas Tropicais", "Florais"], "base": ["Almíscar", "Madeiras", "Âmbar"]},
    "ALHPCR-100":{"topo": ["Rosa", "Frutas"], "coracao": ["Rosa", "Notas Florais"], "base": ["Almíscar", "Baunilha", "Madeiras"]},
    "ALHPER-100":{"topo": ["Especiarias", "Bergamota"], "coracao": ["Notas Amadeiradas", "Orientais"], "base": ["Raízes", "Âmbar", "Almíscar"]},
    "ALHPFS-100":{"topo": ["Flores", "Bergamota"], "coracao": ["Notas Florais Esculpidas"], "base": ["Almíscar", "Madeiras", "Âmbar"]},
    "BHABLU-100":{"topo": ["Bergamota", "Notas Aquáticas"], "coracao": ["Notas Aromáticas Frescas"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "BHACHO-100":{"topo": ["Chocolate", "Bergamota"], "coracao": ["Notas Gourmand"], "base": ["Baunilha", "Âmbar", "Almíscar"]},
    "BHAPEA-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Florais", "Orientais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "BHAPH1-100":{"topo": ["Especiarias", "Bergamota"], "coracao": ["Notas Orientais Profundas"], "base": ["Oud", "Âmbar", "Almíscar"]},
    "BHAPH2-100":{"topo": ["Especiarias", "Bergamota"], "coracao": ["Notas Orientais Profundas"], "base": ["Oud", "Âmbar", "Almíscar"]},
    "BHAVBE-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Florais", "Aromáticas"], "base": ["Madeiras", "Âmbar", "Almíscar"]},
    "BHAVCA-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Florais", "Especiadas"], "base": ["Madeiras", "Âmbar", "Almíscar"]},
    "BHAVKA-100":{"topo": ["Especiarias", "Bergamota"], "coracao": ["Notas Florais", "Madeiras"], "base": ["Almíscar", "Âmbar", "Sândalo"]},
    "BHAVRI-100":{"topo": ["Bergamota", "Notas Tropicais"], "coracao": ["Notas Florais", "Frutadas"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "HALMAN-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "HALMHE-100":{"topo": ["Bergamota", "Notas Frescas"], "coracao": ["Notas Aromáticas", "Florais"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "HALMX-100": {"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "HALWIS-100":{"topo": ["Frutas", "Florais"], "coracao": ["Notas Florais Mágicas"], "base": ["Almíscar", "Baunilha", "Âmbar"]},
    "MAHDEL-100":{"topo": ["Bergamota", "Frutas"], "coracao": ["Notas Florais Brancas"], "base": ["Almíscar", "Baunilha", "Madeiras"]},
    "MAHDEF-100":{"topo": ["Frutas", "Florais"], "coracao": ["Notas Florais Femininas"], "base": ["Almíscar", "Baunilha", "Âmbar"]},
    "MAHJLA-100":{"topo": ["Bergamota", "Notas Frescas"], "coracao": ["Notas Aquáticas", "Florais"], "base": ["Almíscar", "Madeiras", "Âmbar"]},
    "MAHJLV-100":{"topo": ["Bergamota", "Frutas"], "coracao": ["Notas Florais", "Aromáticas"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "MAHPHI-100":{"topo": ["Bergamota", "Notas Frescas"], "coracao": ["Notas Florais Puras"], "base": ["Almíscar", "Madeiras", "Âmbar"]},
    "MAHRSE-100":{"topo": ["Rosa", "Frutas"], "coracao": ["Rosa", "Notas Florais"], "base": ["Almíscar", "Baunilha", "Âmbar"]},
    "MAHSAL-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Âmbar", "Almíscar"]},
    "MAHSAI-100":{"topo": ["Bergamota", "Especiarias Intensas"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Âmbar", "Almíscar"]},
    "MAHSCM-100":{"topo": ["Bergamota", "Notas Verdes"], "coracao": ["Notas Florais", "Aromáticas"], "base": ["Madeiras", "Âmbar", "Almíscar"]},
    "MAHVIC-100":{"topo": ["Bergamota", "Frutas"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Âmbar", "Almíscar"]},
    "MAWFBA-100":{"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "MAWFMA-100":{"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "MAWSYM-100":{"topo": ["Especiarias", "Bergamota"], "coracao": ["Notas Orientais"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "PARMAB-100":{"topo": ["Marshmallow", "Frutas"], "coracao": ["Notas Gourmand", "Florais"], "base": ["Baunilha", "Almíscar", "Âmbar"]},
    "PARMAM-100":{"topo": ["Maçã Verde", "Notas Frescas"], "coracao": ["Notas Florais", "Frutas"], "base": ["Almíscar", "Âmbar", "Madeiras"]},
    "PARMM2-100":{"topo": ["Gengibre", "Lima", "Vodka"], "coracao": ["Notas Aromáticas"], "base": ["Madeiras", "Almíscar", "Âmbar"]},
    "RASHWB-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Aromáticas Intensas"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "RASHWE-100":{"topo": ["Bergamota", "Especiarias"], "coracao": ["Notas Aromáticas Intensas"], "base": ["Âmbar", "Almíscar", "Madeiras"]},
    "RASHWH-100":{"topo": ["Frutas", "Bergamota"], "coracao": ["Notas Florais"], "base": ["Almíscar", "Baunilha", "Âmbar"]},
    "RASHWM-100":{"topo": ["Bergamota", "Notas Aquáticas"], "coracao": ["Notas Aromáticas Marinhas"], "base": ["Almíscar", "Âmbar", "Madeiras"]},
    "ZIMTCA-100":{"topo": ["Caramelo", "Frutas"], "coracao": ["Notas Gourmand"], "base": ["Baunilha", "Âmbar", "Almíscar"]},
    "ZIMTCO-100":{"topo": ["Coco", "Frutas"], "coracao": ["Notas Gourmand"], "base": ["Baunilha", "Âmbar", "Almíscar"]},
}

with open(r"C:\Users\Gamer\Radiant-Fragances\src\Data\produtos.json", encoding="utf-8-sig") as f:
    produtos = json.load(f)

atualizados = 0
for p in produtos:
    # Remove familiasOlfativas de todos
    if "familiasOlfativas" in p:
        del p["familiasOlfativas"]
    # Adiciona notas se existir mapeamento
    pid = p["id"]
    if pid in NOTAS:
        p["notas"] = NOTAS[pid]
        atualizados += 1

with open(r"C:\Users\Gamer\Radiant-Fragances\src\Data\produtos.json", "w", encoding="utf-8") as f:
    json.dump(produtos, f, ensure_ascii=False, indent=2)

print(f"Produtos atualizados com notas: {atualizados}")
print(f"Total de produtos: {len(produtos)}")
